// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/Y2KStudioDropAlert-jsoW6I/App.tsx": () => import("../components/mockups/templates/Y2KStudioDropAlert-jsoW6I/App.tsx"),
  "./components/mockups/templates/Y2KStudioDropAlert-q-uIp-/App.tsx": () => import("../components/mockups/templates/Y2KStudioDropAlert-q-uIp-/App.tsx")
};
